### Templates

### Logic
dist: bionic

language: bash

services:
- docker

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - qemu-user-static

#stages:
#- name: build-binary
#- name: build-docker

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json

script:
- travis_wait 40 ./build-script.sh ${BUILD_TYPE}

matrix:
  include:
  - env: BUILD_TYPE=docker
  - env: BUILD_TYPE=tar ARCH_LABEL=i386 BUILD_GOOS=linux BUILD_GOARCH=386
  - env: BUILD_TYPE=tar ARCH_LABEL=i386 BUILD_GOOS=windows BUILD_GOARCH=386
  - env: BUILD_TYPE=tar ARCH_LABEL=amd64 BUILD_GOOS=linux BUILD_GOARCH=amd64
  - env: BUILD_TYPE=tar ARCH_LABEL=amd64 BUILD_GOOS=darwin BUILD_GOARCH=amd64
  - env: BUILD_TYPE=tar ARCH_LABEL=amd64 BUILD_GOOS=windows BUILD_GOARCH=amd64
  - env: BUILD_TYPE=tar ARCH_LABEL=armel BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=5
  - env: BUILD_TYPE=tar ARCH_LABEL=armhf BUILD_GOOS=linux BUILD_GOARCH=arm BUILD_GOARM=6
  - env: BUILD_TYPE=tar ARCH_LABEL=arm64 BUILD_GOOS=linux BUILD_GOARCH=arm64
