### Templates

### Logic
dist: bionic

language: bash

services:
- docker

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - qemu-user-static

stages:
- name: build-binary
- name: build-docker

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json

script:
- ./build-script.sh ${TRAVIS_BUILD_STAGE_NAME}

matrix:
  include:
  - stage: build-binary
    env: ARCH_LABEL=i386 BUILD_GOOS=linux
  - env: ARCH_LABEL=amd64 BUILD_GOOS=linux
  - env: ARCH_LABEL=armel BUILD_GOOS=linux
  - env: ARCH_LABEL=armhf BUILD_GOOS=linux
  - env: ARCH_LABEL=arm64 BUILD_GOOS=linux
  - stage: build-docker
    env: BUILD_TEST=hi
