_build: &_build
  stage: build
  deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    skip_cleanup: true
    "on":
      tags: true
    file_glob: true
    file: artifacts/*
  - provider: script
    skip_cleanup: true
    "on":
      tags: true
      condition: ${DOCKER_BUILT} = true
    script: ${TRAVIS_BUILD_DIR}/deploy_docker.sh
  script:
  - cd ${GOPATH}/src/github.com/gravitational/teleport && make release && bash ${TRAVIS_BUILD_DIR}/rename.sh
  - if [[ ${BUILD_GOOS} == "linux" && -e ${TRAVIS_BUILD_DIR}/Dockerfile.${ARCH_LABEL} ]]; then cd ${TRAVIS_BUILD_DIR} && mkdir temp/ && tar -xvf artifacts/teleport-*.tar.gz -C ./temp --strip-components=1 teleport/teleport teleport/tctl teleport/tsh ; fi
  - if [[ ${BUILD_GOOS} == "linux" && -e ${TRAVIS_BUILD_DIR}/Dockerfile.${ARCH_LABEL} ]]; then cd ${TRAVIS_BUILD_DIR} && docker build --pull --no-cache -t ${DOCKER_TAG}:${ARCH_LABEL}-${REMOTE_BRANCH} -f Dockerfile.${ARCH_LABEL} . && export DOCKER_BUILT=true ; fi
  before_script:
  - export ALT_BRANCH=$(tail -n1 ${TRAVIS_BUILD_DIR}/VERSIONS)
  - export REMOTE_BRANCH=${TRAVIS_TAG:-${ALT_BRANCH}}
  - export GOOS=${BUILD_GOOS}
  - export GOARCH=${BUILD_GOARCH}
  - if [[ -n "${BUILD_GOARM}" ]]; then export GOARM=${BUILD_GOARM} ; fi
  - if [[ -n "${BUILD_CC}" ]]; then export CC=${BUILD_CC} ; fi
  - echo "GOOS ${GOOS}, GOARCH ${GOARCH}, ARCH_LABEL ${ARCH_LABEL}, REMOTE_BRANCH ${REMOTE_BRANCH}, CC ${CC}, ALT_BRANCH ${ALT_BRANCH}"
  - git clone -q --branch=${REMOTE_BRANCH} https://github.com/gravitational/teleport.git ${GOPATH}/src/github.com/gravitational/teleport && cd ${GOPATH}/src/github.com/gravitational/teleport && git checkout -qf ${REMOTE_BRANCH} 
  after_success:
  - find ${TRAVIS_BUILD_DIR}/artifacts
  - cd ${TRAVIS_BUILD_DIR}

_arm_pkgs: &_arm_pkgs
  addons:
    apt:
      update: true
      packages:
      - gcc-multilib
      - gcc-4.7-arm-linux-gnueabi
      - gcc-arm-linux-gnueabi
      - libc6-armel-cross
      - libc6-dev-armel-cross
      - libc6-armhf-armel-cross
      - libc6-dev-armhf-armel-cross

_386_pkgs: &_386_pkgs
  addons:
    apt:
      update: true
      packages:
      - gcc-multilib
      - libc6-dev-i386

language: go

go: "1.10"

services:
- docker

stages:
- name: build

jobs:
  include:
  - name: linux i386
    env:
    - BUILD_GOOS=linux
    - BUILD_GOARCH=386
    - ARCH_LABEL=i386
    <<: *_build
    <<: *_386_pkgs
  - name: linux amd64
    env:
    - BUILD_GOOS=linux
    - BUILD_GOARCH=amd64
    - ARCH_LABEL=amd64
    <<: *_build
  - name: linux armel
    env:
    - BUILD_GOOS=linux
    - BUILD_GOARCH=arm
    - BUILD_GOARM=5
    - BUILD_CC=arm-linux-gnueabi-gcc
    - ARCH_LABEL=armel
    <<: *_build
    <<: *_arm_pkgs
  - name: linux armhf
    env:
    - BUILD_GOOS=linux
    - BUILD_GOARCH=arm
    - BUILD_GOARM=6
    - BUILD_CC=arm-linux-gnueabi-gcc
    - ARCH_LABEL=armhf
    <<: *_build
    <<: *_arm_pkgs
  - name: windows i386
    env:
    - BUILD_GOOS=windows
    - BUILD_GOARCH=386
    - ARCH_LABEL=i386
    <<: *_build
  - name: windows amd64
    env:
    - BUILD_GOOS=windows
    - BUILD_GOARCH=amd64
    - ARCH_LABEL=amd64
    <<: *_build
#  - name: linux arm64
#    env:
#    - BUILD_GOOS=linux
#    - BUILD_GOARCH=arm64
#    - BUILD_CC=arm-linux-gnueabi-gcc
#    - ARCH_LABEL=arm64
#    <<: *_build
#    <<: *_arm_pkgs
