---
# appveyor.yml
version: 0.0.{build}
skip_non_tags: true

image:
- Ubuntu1804

environment:
  GOPATH: /home/appveyor/go

clone_folder: ${HOME}/go/src/github.com/${APPVEYOR_REPO_NAME}

stack: go 1.10

build_script:
- sh: sudo apt-get update -y ; sudo apt-get install -y gcc-arm-linux-gnueabi
- sh: ${HOME}/go/src/github.com/${APPVEYOR_REPO_NAME}/build.sh

artifacts:
- path: 'artifacts/*'

deploy:
  description: '> TODO: Write a description'
  provider: GitHub
  auth_token:
    secure: QG6n+fzetSxrI2uruHJyDO/YiBkvqOdFYdmYfSWG0d/QKYuIx2xrz9guxKrT7DYw
  artifact: /*/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
