---
# appveyor.yml
version: 0.0.{build}
skip_non_tags: true

image:
- Ubuntu1804

environment:
  GOPATH: /home/appveyor/go

clone_folder: ${HOME}/go/src/github.com/${APPVEYOR_REPO_NAME}

stack: go 1.10

install:
- sh: sudo apt-get update -y ; sudo apt-get install -y gcc-arm-linux-gnueabi

build_script:
- sh: ${HOME}/go/src/github.com/${APPVEYOR_REPO_NAME}/build.sh
- sh: if [ $(ls -1 ${APPVEYOR_BUILD_FOLDER}/artifacts/ | wc -l) -gt 0 ]; then export ARTIFACTS_EXIST=true ; else export ARTIFACTS_EXIST=false ; fi

artifacts:
- name: bundles
  path: 'artifacts/*'

deploy:
- provider: GitHub
  description: '> TODO: Write a description'
  auth_token:
    secure: QG6n+fzetSxrI2uruHJyDO/YiBkvqOdFYdmYfSWG0d/QKYuIx2xrz9guxKrT7DYw
  artifact: bundles
  draft: false
  prerelease: false
  on:
#    branch: master
    APPVEYOR_REPO_TAG: true
    ARTIFACTS_EXIST: true
