meta:
  description: multi-arch builds of teleport
  vendor: Zaephor <Zaephor@users.noreply.github.com>
  maintainer: Zaephor <Zaephor@users.noreply.github.com>
files:
  "/usr/local/bin/teleport":
    file: tmp/teleport
    mode: "0755"
    user: "root"
  "/usr/local/bin/tctl":
    file: tmp/tctl
    mode: "0755"
    user: "root"
  "/usr/local/bin/tsh":
    file: tmp/tsh
    mode: "0755"
    user: "root"
  "/usr/local/bin/tbot":
    file: tmp/tbot
    mode: "0755"
    user: "root"
  "/etc/init/teleport.conf":
    file: ci/upstart-teleport.conf
    mode: "0644"
    user: "root"
units:
  - ci/systemd-teleport.service
