# /etc/init/teleport.conf — Teleport Service (Upstart)
# Equivalent of systemd-teleport.service for Ubuntu 14.04 / Upstart systems

description "Teleport Service"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit unlimited

reload signal HUP

limit nofile 524288 524288

pre-start script
    mkdir -p -m0700 /var/lib/teleport
end script

script
    [ -r /etc/default/teleport ] && . /etc/default/teleport
    exec /usr/local/bin/teleport start --config /etc/teleport.yaml --pid-file=/run/teleport.pid
end script
