on:
  pull_request:
  workflow_dispatch:
    inputs:
      tp_version:
        description: 'Teleport Version'
        required: true
        default: 'v2.3.0'
#  push:
#    branches:
#      - ci

env:
  UPSTREAM: github.com/gravitational/teleport

jobs:
  build-linux:
    runs-on: ${{ matrix.build_os || 'ubuntu-latest' }}
    #container:
    #  image: ${{ matrix.container_image || null }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            go_os: linux
            go_arch: amd64
            container_image: 'ubuntu:14.04'
            cargo_target: x86_64-unknown-linux-gnu
          - name: linux-i386
            go_os: linux
            go_arch: 386
            container_image: 'ubuntu:14.04'
            cargo_target: i686-unknown-linux-gnu
          - name: linux-arm64
            go_os: linux
            go_arch: arm64
            cc: aarch64-linux-gnu-gcc
            container_image: 'ubuntu:20.04'
            cargo_target: aarch64-unknown-linux-gnu
          - name: linux-armhf
            go_os: linux
            go_arch: arm
            go_arm: 6
            go_experiment: nounified
            cc: arm-linux-gnueabihf-gcc
            container_image: 'ubuntu:14.04'
            cargo_target: arm-unknown-linux-gnueabihf
          - name: linux-armel
            go_os: linux
            go_arch: arm
            go_arm: 5
            cc: arm-linux-gnueabi-gcc
            container_image: 'ubuntu:14.04'

#          - name: linux-mips
#            go_os: linux
#            go_arch: mips
#            cc: mips-linux-gnu-gcc
#            container_image: 'ubuntu:20.04'

#          - name: darwin-amd64
#            go_os: darwin
#            go_arch: amd64
#            build_os: macos-latest
#          - name: darwin-arm64
#            go_os: darwin
#            go_arch: arm64
#            build_os: macos-latest
#          - name: windows-amd64
#            go_os: windows
#            go_arch: amd64
#            build_os: windows-latest
    steps:
      - name: checkout ci
        uses: actions/checkout@main
        with:
          path: ci
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}

      - name: vars
        id: vars
        run: |
          echo "pwd=$PWD" | tee -a ${GITHUB_OUTPUT}
          export RECENT=$(echo "ver_recent=$(grep -v '^#' ci/VERSIONS | tail -n1)" | tee -a ${GITHUB_OUTPUT})
          export LATEST=$(echo "ver_latest=$(cat ci/LATEST)" | tee -a ${GITHUB_OUTPUT})
          if [ -n "${{ github.event.inputs.tp_version }}" ]; then
            echo "build_ver=${{ github.event.inputs.tp_version }}" | tee -a ${GITHUB_OUTPUT}
          else
            echo "build_ver=${RECENT#*=}" | tee -a ${GITHUB_OUTPUT}
          fi

      - name: checkout source
        uses: actions/checkout@main
        with:
          ref: ${{ steps.vars.outputs.build_ver }}
          path: go/src/${{ env.UPSTREAM }}
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}

      - name: debug
        id: debug
        run: |
          echo "::group::pwd"
          echo $PWD
          echo "::endgroup::"
          echo "::group::find"
          find .
          echo "::endgroup::"

      - uses: actions/setup-go@main
        id: setup-go
        with:
          go-version-file: 'go/src/${{ env.UPSTREAM }}/go.mod'
          cache-dependency-path: 'go/src/${{ env.UPSTREAM }}/go.sum'
          check-latest: true

      - name: prep && build (ubuntu:14.04)
        uses: docker://ubuntu:14.04
        if: matrix.container_image == 'ubuntu:14.04'
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "bash ci/prep.sh && bash ci/build.sh"
        env:
          CC: ${{ matrix.cc }}
          ENV_OS: ${{ matrix.build_os || 'ubuntu-latest' }}
          GOPATH: ${{ steps.vars.outputs.pwd }}/go
          GO_ARCH: ${{ matrix.go_arch }}
          GO_ARM: ${{ matrix.go_arm || null }}
          GO_EXPERIMENT: ${{ matrix.go_experiment }}
          GO_OS: ${{ matrix.go_os }}
          GO_VERSION: ${{ steps.setup-go.outputs.go-version }}
          REF_NAME: ${{ matrix.name }}
          REF_PWD: ${{ steps.vars.outputs.pwd }}
          REF_VER: ${{ steps.vars.outputs.build_ver }}
          UPSTREAM: ${{ env.UPSTREAM }}
      - name: prep && build (ubuntu:20.04)
        uses: docker://ubuntu:20.04
        if: matrix.container_image == 'ubuntu:20.04'
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "bash ci/prep.sh && bash ci/build.sh"
        env:
          CC: ${{ matrix.cc }}
          ENV_OS: ${{ matrix.build_os || 'ubuntu-latest' }}
          GOPATH: ${{ steps.vars.outputs.pwd }}/go
          GO_ARCH: ${{ matrix.go_arch }}
          GO_ARM: ${{ matrix.go_arm || null }}
          GO_EXPERIMENT: ${{ matrix.go_experiment }}
          GO_OS: ${{ matrix.go_os }}
          REF_NAME: ${{ matrix.name }}
          REF_PWD: ${{ steps.vars.outputs.pwd }}
          REF_VER: ${{ steps.vars.outputs.build_ver }}
          UPSTREAM: ${{ env.UPSTREAM }}

      - name: tar
        run: |
          sudo chown $(id -u):$(id -g) "${{ steps.vars.outputs.pwd }}/dist"
          cd "${{ steps.vars.outputs.pwd }}/dist"
          tar czf teleport-${{ steps.vars.outputs.build_ver }}-${{ matrix.name }}.tar.gz teleport/

      - uses: actions/upload-artifact@main
        if: github.event_name != 'pull_request'
        with:
          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.build_ver }}-${{ matrix.name }}
          path: dist/
          retention-days: 1

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request'
        with:
          tag_name: ${{ steps.vars.outputs.build_ver }}
          files: |
            dist/teleport-${{ steps.vars.outputs.build_ver }}-${{ matrix.name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: [build-linux]
    if: always() && github.event_name != 'pull_request'
    steps:
      - name: checkout ci
        uses: actions/checkout@main
        with:
          ref: ci
          path: ci
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}

      - name: vars
        id: vars_ci
        run: |
          echo "LATEST=$(cat ci/LATEST)" | tee -a $GITHUB_OUTPUT
          if [[ -n "${{ github.event.inputs.tp_version }}" ]]; then
                  INPUT="${{ github.event.inputs.tp_version }}"
          else
                  INPUT=$(tail -n1 ci/VERSIONS)
          fi
          echo "REF=${INPUT}" | tee -a $GITHUB_OUTPUT
          if [[ "$(cat ci/LATEST)" == "${INPUT}" ]]; then
                  echo "TAG=latest" | tee -a $GITHUB_OUTPUT
          else
                  echo "TAG=dev" | tee -a $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: draconrose/teleport,ghcr.io/${{ github.repository_owner  }}/teleport
          flavor: |
            latest=false
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}},value=${{ steps.vars_ci.outputs.REF }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.vars_ci.outputs.REF }}
            type=semver,pattern=v{{major}},value=${{ steps.vars_ci.outputs.REF }}
            type=raw,${{ steps.vars_ci.outputs.TAG }}

      - name: Identify platforms
        id: plat
        run: |
          ARCHES=""
          for arch in 'amd64,amd64' 'armhf,arm/v7' 'arm64,arm64/v8'; do
            EXISTS=$(curl --silent --head https://github.com/Zaephor/teleport/releases/download/${{ steps.vars_ci.outputs.REF }}/teleport-${{ steps.vars_ci.outputs.REF }}-linux-${arch%,*}.tar.gz | awk '/^HTTP/{print $2}')
            if [[ -n "${EXISTS}" && "${EXISTS}" != "40"* ]]; then
              if [[ -n "${ARCHES}" ]]; then
                  ARCHES+=","
              fi
              ARCHES+="linux/${arch#*,}"
            fi
          done
          echo "ARCHES=${ARCHES}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ci
          platforms: ${{ steps.plat.outputs.ARCHES }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            RELEASE=${{ steps.vars_ci.outputs.REF }}

  dispatch:
    runs-on: ubuntu-latest
    needs: [build-linux,docker]
    if: github.event_name != 'pull_request'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: check

