on:
  pull_request:
  workflow_dispatch:
    inputs:
      tp_version:
        description: 'Teleport Version'
        required: true
        default: 'v2.3.0'
  push:
    branches:
      - ci

env:
  UPSTREAM: github.com/gravitational/teleport

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ci
        uses: actions/checkout@main
        with:
          ref: ci
          path: ci
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
      - id: tp-ver
        shell: bash
        run: |
          echo "pwd=$PWD" | tee -a ${GITHUB_OUTPUT}
          export RECENT=$(echo "ver_recent=$(grep -v '^#' ci/VERSIONS | tail -n1)" | tee -a ${GITHUB_OUTPUT})
          export LATEST=$(echo "ver_latest=$(cat ci/LATEST)" | tee -a ${GITHUB_OUTPUT})
          if [ -n "${{ github.event.inputs.tp_version }}" ]; then
            echo "build_ver=${{ github.event.inputs.tp_version }}" | tee -a ${GITHUB_OUTPUT}
          else
            echo "build_ver=${RECENT#*=}" | tee -a ${GITHUB_OUTPUT}
          fi
      - name: checkout source
        uses: actions/checkout@main
        with:
          ref: ${{ steps.tp-ver.outputs.build_ver }}
          path: go/src/${{ env.UPSTREAM }}
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
      - id: go-ver
        shell: bash
        run: |
          GO_VER=$(awk '/^go /{print $NF}' "go/src/${{ env.UPSTREAM }}/go.mod")
          echo "go_ver=${GO_VER}" | tee -a ${GITHUB_OUTPUT}
      - uses: docker://ubuntu:14.04
        with:
          entrypoint: /bin/bash
          args: |
            -e -c "
            echo '::group::apt-get update'
            sudo apt-get update
            echo '::endgroup::'
            echo '::group::apt-get install'
            sudo apt-get -f -y install curl wget git libpam0g-dev binutils bison gcc make binutils-multiarch build-essential bsdmainutils binutils-2.26
            echo '::endgroup::'
            echo '::group::install gvm'
            bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer) || true
            source /github/home/.gvm/scripts/gvm
            echo '::endgroup::'
            "
      - id: debug
        shell: bash
        run: |
          find .
          exit 1


  build-linux:
    runs-on: ubuntu-latest
    needs: [build-go]
    steps:
      - id: debug
        shell: bash
        run: |
          find .
          exit 1
  docker:
    runs-on: ubuntu-latest
    needs: [build-linux]
    if: always() && github.event_name != 'pull_request'
    steps:
      - name: checkout ci
        uses: actions/checkout@main
        with:
          ref: ci
          path: ci
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}

      - name: vars
        id: vars_ci
        run: |
          echo "LATEST=$(cat ci/LATEST)" | tee -a $GITHUB_OUTPUT
          if [[ -n "${{ github.event.inputs.tp_version }}" ]]; then
                  INPUT="${{ github.event.inputs.tp_version }}"
          else
                  INPUT=$(tail -n1 ci/VERSIONS)
          fi
          echo "REF=${INPUT}" | tee -a $GITHUB_OUTPUT
          if [[ "$(cat ci/LATEST)" == "${INPUT}" ]]; then
                  echo "TAG=latest" | tee -a $GITHUB_OUTPUT
          else
                  echo "TAG=dev" | tee -a $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: draconrose/teleport,ghcr.io/${{ github.repository_owner  }}/teleport
          flavor: |
            latest=false
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}},value=${{ steps.vars_ci.outputs.REF }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.vars_ci.outputs.REF }}
            type=semver,pattern=v{{major}},value=${{ steps.vars_ci.outputs.REF }}
            type=raw,${{ steps.vars_ci.outputs.TAG }}

      - name: Identify platforms
        id: plat
        run: |
          ARCHES=""
          for arch in 'amd64,amd64' 'armhf,arm/v7' 'arm64,arm64/v8'; do
            EXISTS=$(curl --silent --head https://github.com/Zaephor/teleport/releases/download/${{ steps.vars_ci.outputs.REF }}/teleport-${{ steps.vars_ci.outputs.REF }}-linux-${arch%,*}.tar.gz | awk '/^HTTP/{print $2}')
            if [[ -n "${EXISTS}" && "${EXISTS}" != "40"* ]]; then
              if [[ -n "${ARCHES}" ]]; then
                  ARCHES+=","
              fi
              ARCHES+="linux/${arch#*,}"
            fi
          done
          echo "ARCHES=${ARCHES}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ci
          platforms: ${{ steps.plat.outputs.ARCHES }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            RELEASE=${{ steps.vars_ci.outputs.REF }}

  dispatch:
    runs-on: ubuntu-latest
    needs: [build-linux,docker]
    if: github.event_name != 'pull_request'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: check
