on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    type:
      - check
#  schedule:
#  - cron: '*/20 * * * *'

env:
  REPO_UPSTREAM: https://github.com/gravitational/teleport.git
  AWK_FILTER_TAG: awk -F '/' '/refs\/tags/ && $NF ~ /v[[:digit:]]+(\.[[:digit:]]+){2}$/{print $NF}'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: checkout ci
      uses: actions/checkout@v4
      with:
        ref: ci
        fetch-depth: 1
        token: ${{ secrets.GH_PAT }}

    - name: Identify LATEST
      run: |
        git ls-remote --tags ${{ env.REPO_UPSTREAM }} | ${{ env.AWK_FILTER_TAG }} | sort -Vru | head -n 1 > LATEST
        comm --nocheck-order -23 <(git ls-remote --tags https://github.com/${{ github.repository }} | ${{ env.AWK_FILTER_TAG }} | sort -Vu) <(sort -Vu VERSIONS) | head -n 1 >> VERSIONS
        if ! git diff-index --quiet HEAD --; then
          echo "IF result: $?"
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add LATEST VERSIONS
          git commit -m "ci: Bump LATEST($(cat LATEST)) and VERSIONS($(tail -n 1 VERSIONS))"
          git push origin ci --quiet
        fi
